spring.application.name=demo
google.books.base-url=https://www.googleapis.com/books/v1

app.messages.book.saved.success=Book saved successfully to your list.
app.messages.book.allready.exists=This book already exists in your collection.
app.messages.book.not.found=Book details could not be retrived from the API.
